[package]
name = "t-rec"
version = "0.1.0"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"

[dependencies]
#core-graphics = "0.22"
#core-foundation = "0.9"
foreign-types-shared = "0.3"
image = "0.23"
ctrlc = "3.1"
glob = "0.3"
objc-foundation = "0.1.1"
objc_id = "0.1.1"
libproc = "0.9"
anyhow = "1.0"
tempdir = "0.3"

#[patch.crates-io]
core-graphics = { path = "../core-foundation-rs/core-graphics" }
core-foundation = { path = "../core-foundation-rs/core-foundation" }
core-foundation-sys = { path = "../core-foundation-rs/core-foundation-sys" }
