[package]
name = "t-rec"
version = "0.1.0-beta.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
homepage = "https://github.com/sassman/t-rec-rs"
readme = "README.md"
keywords = ["recorder", "image", "terminal", "gif", "commandline"]
categories = ["multimedia::images", "command-line-utilities"]
repository = "https://github.com/sassman/t-rec-rs"
exclude = [".ci/*", ".gitignore"]

[dependencies]
#core-graphics = "0.22"
#core-foundation = "0.9"
foreign-types-shared = "0.3"
image = "0.23"
glob = "0.3"
objc-foundation = "0.1.1"
objc_id = "0.1.1"
libproc = "0.9"
anyhow = "1.0"
tempdir = "0.3"

#[patch.crates-io]
core-graphics = { path = "../core-foundation-rs/core-graphics" }
core-foundation = { path = "../core-foundation-rs/core-foundation" }
core-foundation-sys = { path = "../core-foundation-rs/core-foundation-sys" }
